/**
 * @generated by ars episode create
 * @episode ep002
 *
 * ars audio generate will merge timed subtitle phrases into this file.
 */

import { type SubtitlePhrase } from "../../engine/shared/subtitle";

export const subtitles: Record<string, SubtitlePhrase[]> = {};
