/**
 * @generated by sync_audio.ts
 * @episode ep001
 *
 * Subtitle timing based on OmniVoice audio durations
 * (voice design: 男，中年，低音调, speed: 0.8).
 */

import { type SubtitlePhrase } from "../../engine/shared/subtitle";

export const subtitles: Record<string, SubtitlePhrase[]> = {
  "location": [
    { text: "這是阿萬今年在媽祖生那天，帶著相機走進的一間宮廟。", startTime: 0, endTime: 5 },
    { text: "不是什麼大廟，但一早香爐就已經滿了。", startTime: 5, endTime: 9.9 }
  ],
  "prep-altar": [
    { text: "供桌上排得滿滿的。", startTime: 0, endTime: 4.3 },
    { text: "壽桃、紅龜粿、鮮花，每一樣都是信徒天還沒亮就準備好的。", startTime: 4.3, endTime: 8.6 }
  ],
  "prep-incense": [
    { text: "捻香的人一個接一個。", startTime: 0, endTime: 3.3 },
    { text: "煙往上飄，整間廟像罩了一層薄薄的霧。", startTime: 3.3, endTime: 6.5 }
  ],
  "prep-ceremony": [
    { text: "儀式開始的時候，鐘鼓聲一響，所有人都安靜下來。", startTime: 0, endTime: 3.9 },
    { text: "那種氛圍，不在現場很難體會。", startTime: 3.9, endTime: 7.8 }
  ],
  "climax-crowd": [
    { text: "接近中午，人潮漸漸湧進來。", startTime: 0, endTime: 2.5 },
    { text: "廟埕幾乎沒有轉身的地方。", startTime: 2.5, endTime: 5.1 }
  ],
  "climax-firecrackers": [
    { text: "鞭炮聲一起，整條街都在震。", startTime: 0, endTime: 3.1 },
    { text: "不是吵，是一種——慶典該有的聲音。", startTime: 3.1, endTime: 6.2 }
  ],
  "climax-performance": [
    { text: "陣頭一來，氣氛又推到另一個高點。", startTime: 0, endTime: 4 },
    { text: "鑼鼓、腳步、喊聲——現場的節奏不需要解說。", startTime: 4, endTime: 8 }
  ],
  "humanity-food": [
    { text: "廟口這時候最熱鬧的不只是神明，還有攤販。", startTime: 0, endTime: 4.9 },
    { text: "蒸氣、油煙、人聲混在一起，就是廟會的氣味。", startTime: 4.9, endTime: 9.8 }
  ],
  "humanity-meal": [
    { text: "廟方煮了一大鍋平安麵。", startTime: 0, endTime: 3.4 },
    { text: "不分彼此，路過的人都可以坐下來吃一碗。", startTime: 3.4, endTime: 6.7 }
  ],
  "humanity-people": [
    { text: "媽祖生，不只是拜拜。", startTime: 0, endTime: 5.1 },
    { text: "它是阿公阿嬤一年一度出門的理由，是小孩第一次聞到鞭炮味的那天。", startTime: 5.1, endTime: 10.2 }
  ],
  "closing": [
    { text: "廟會的熱鬧會散，但畫面留下來了。", startTime: 0, endTime: 2.8 },
    { text: "我是阿萬，我們下次見。", startTime: 2.8, endTime: 5.5 }
  ]
};
