/**
 * ARS audio sync tool — reads durations.json from OmniVoice TTS output,
 * auto-generates subtitles.ts and updates durationInSeconds in the episode file.
 *
 * Usage:
 *   npx tsx .ars/sync_audio.ts <epId> [--series <seriesId>]
 *
 * Example:
 *   npx tsx .ars/sync_audio.ts ep001
 *
 * Requires: durations.json in the audio directory.
 */

import fs from "fs";
import path from "path";

// ── Config ──
const ROOT = path.resolve(__dirname, "..");
const SERIES = process.env.ARS_SERIES || "Youtube-studio";

const EP_ID = process.argv[2];
if (!EP_ID) {
  console.error("Usage: npx tsx .ars/sync_audio.ts <epId> [--series <seriesId>]");
  process.exit(1);
}

// Parse optional --series flag
const seriesIdx = process.argv.indexOf("--series");
const SERIES_ID = seriesIdx !== -1 ? process.argv[seriesIdx + 1] : SERIES;

// ── Paths ──
const AUDIO_DIR = path.join(ROOT, "public", "episodes", SERIES_ID, EP_ID, "audio");
const DURATIONS_PATH = path.join(AUDIO_DIR, "durations.json");
const EPISODE_PATH = path.join(ROOT, "src", "episodes", SERIES_ID, `${EP_ID}.ts`);
const SUBTITLES_PATH = path.join(ROOT, "src", "episodes", SERIES_ID, `${EP_ID}.subtitles.ts`);

// ── Main ──
if (!fs.existsSync(DURATIONS_PATH)) {
  console.error(`❌ durations.json not found at ${DURATIONS_PATH}`);
  console.error("   Run omnivoice_tts.py first to generate audio and durations.");
  process.exit(1);
}

const meta = JSON.parse(fs.readFileSync(DURATIONS_PATH, "utf-8"));
const durations: Record<string, number> = meta.durations;

if (!fs.existsSync(EPISODE_PATH)) {
  console.error(`❌ Episode file not found: ${EPISODE_PATH}`);
  process.exit(1);
}

const epSource = fs.readFileSync(EPISODE_PATH, "utf-8");

// Extract narration text for each step
const stepPattern = /id:\s*['"]([^'"]+)['"]\s*,[\s\S]*?narration:\s*['"]([^'"]*?)['"]/g;
const narrations: Record<string, string> = {};
let match;
while ((match = stepPattern.exec(epSource)) !== null) {
  narrations[match[1]] = match[2];
}

// ── 1. Update subtitles.ts ──
function splitText(text: string): string[] {
  // Split by Chinese/English punctuation
  const parts = text.split(/([。！？\n]|[.!?](?=\s|\n))/);
  const sentences: string[] = [];
  for (const p of parts) {
    if (!p) continue;
    if (/^[。！？\n.!?]$/.test(p) && sentences.length > 0) {
      sentences[sentences.length - 1] += p;
    } else if (p.trim()) {
      sentences.push(p);
    }
  }
  return sentences.map(s => s.trim()).filter(Boolean);
}

const subtitleEntries: string[] = [];
for (const [stepId, duration] of Object.entries(durations)) {
  const text = narrations[stepId];
  if (!text) {
    console.warn(`⚠️  No narration found for step "${stepId}", skipping subtitle entry.`);
    continue;
  }

  const sentences = splitText(text);
  if (sentences.length === 0) continue;

  const timePerSentence = duration / sentences.length;
  const phrases = sentences.map((s, i) => {
    const start = +(i * timePerSentence).toFixed(1);
    const end = +((i + 1) * timePerSentence).toFixed(1);
    return `    { text: ${JSON.stringify(s)}, startTime: ${start}, endTime: ${end} }`;
  });

  subtitleEntries.push(`  ${JSON.stringify(stepId)}: [\n${phrases.join(",\n")}\n  ]`);
}

const subtitleContent = `/**
 * @generated by sync_audio.ts
 * @episode ${EP_ID}
 *
 * Subtitle timing based on OmniVoice audio durations
 * (voice design: ${meta.instruct}, speed: ${meta.speed}).
 */

import { type SubtitlePhrase } from "../../engine/shared/subtitle";

export const subtitles: Record<string, SubtitlePhrase[]> = {
${subtitleEntries.join(",\n")}
};
`;

fs.writeFileSync(SUBTITLES_PATH, subtitleContent, "utf-8");
console.log(`✅ Subtitles written: ${SUBTITLES_PATH}`);

// ── 2. Update durationInSeconds in ep.ts ──
let updatedEp = epSource;
let changedCount = 0;

for (const [stepId, duration] of Object.entries(durations)) {
  const rounded = Math.ceil(duration);
  const text = narrations[stepId];
  if (!text) continue;

  // Escape for regex
  const escapedText = text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  // Match the specific step's durationInSeconds
  const regex = new RegExp(
    `(narration:\\s*'${escapedText}',\\s*\\n\\s*durationInSeconds:\\s*)\\d+`,
    "g"
  );
  const newStr = `$1${rounded}`;
  const before = updatedEp;
  updatedEp = updatedEp.replace(regex, newStr);
  if (updatedEp !== before) changedCount++;
}

if (changedCount > 0) {
  fs.writeFileSync(EPISODE_PATH, updatedEp, "utf-8");
  console.log(`✅ Updated durationInSeconds for ${changedCount} steps in ${EPISODE_PATH}`);
} else {
  console.log("ℹ️  No durationInSeconds changes needed.");
}

// ── Summary ──
const totalDuration = Math.ceil(Object.values(durations).reduce((a, b) => a + b, 0));
const introMatch = epSource.match(/id:\s*['"]intro['"].*?durationInSeconds:\s*(\d+)/s);
const introDuration = introMatch ? parseInt(introMatch[1]) : 0;
console.log(`\n📊 Summary: ${Object.keys(durations).length} steps, ${totalDuration + introDuration}s total`);
console.log(`   Run: npx ars episode validate ${EP_ID}`);
